name: proteam_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  fake_cloud_firestore: ^2.4.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.8
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
