name: proteam_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.16.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  fake_cloud_firestore: ^2.4.9
  firebase_auth: ^4.19.3
  firebase_auth_mocks: ^0.13.0
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.8
  google_nav_bar: ^5.0.6
  image_picker: ^1.1.0
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/
