// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWKjpbKYjwN26p_NVDdzuyPNY6zuKHgKE',
    appId: '1:285081369780:web:db1e28b805aee92f5debe1',
    messagingSenderId: '285081369780',
    projectId: 'proteam-app',
    authDomain: 'proteam-app.firebaseapp.com',
    storageBucket: 'proteam-app.appspot.com',
    measurementId: 'G-GL5YPE13FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjUcAc6OnM5-gcd16jl6MuCvIJHBTjbj4',
    appId: '1:285081369780:android:83623daecc88932f5debe1',
    messagingSenderId: '285081369780',
    projectId: 'proteam-app',
    storageBucket: 'proteam-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_NDoF2zhGv78KkEVjwP3sfabatoCmRZI',
    appId: '1:285081369780:ios:03506cbd32830fcd5debe1',
    messagingSenderId: '285081369780',
    projectId: 'proteam-app',
    storageBucket: 'proteam-app.appspot.com',
    iosBundleId: 'com.example.proteamApp',
  );
}
